app:
  base-url: http://localhost:8080
  frontend-url: http://localhost:5173
  google:
    client-id: ${GOOGLE_CLIENT_ID}

jwt:
  key:
    id: "room-booking-key-2025"
    private-path: classpath:certs/private.pem
    public-path: classpath:certs/public.pem
  refresh:
    expiration: 2592000000 # 30 days in milliseconds

spring:
  config:
    activate:
      on-profile: dev

  jackson:
    time-zone: UTC
    default-property-inclusion: non_null

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/room_booking_db?stringtype=unspecified
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: public

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show_sql: false
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: http://localhost:5173/auth/google-callback
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: sub

open:
  api:
    serverUrl: http://localhost:8080
    title: Room Booking API (Dev)
    version: v1.0.0
    serverName: Room Booking Backend API
    description: API documentation for Room Booking project.

logging:
  level:
    root: INFO
    com.thang.roombooking: DEBUG

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080