CREATE TABLE booking_histories
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    booking_id   BIGINT                                  NOT NULL,
    action       VARCHAR(255),
    status_after VARCHAR(255),
    performed_by VARCHAR(255),
    note         VARCHAR(255),
    CONSTRAINT pk_booking_histories PRIMARY KEY (id)
);

ALTER TABLE booking_histories
    ADD CONSTRAINT FK_BOOKING_HISTORIES_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);