CREATE TABLE penalty_records
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    action_type VARCHAR(50)                             NOT NULL,
    is_active   BOOLEAN                                 NOT NULL DEFAULT TRUE,
    start_date  TIMESTAMP WITH TIME ZONE                NOT NULL,
    end_date    TIMESTAMP WITH TIME ZONE                NOT NULL,
    reason      TEXT                            NOT NULL,
    CONSTRAINT pk_penalty_records PRIMARY KEY (id)
);

ALTER TABLE penalty_records
    ADD CONSTRAINT fk_penalty_records_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE booking_violations
    ADD source VARCHAR(20) DEFAULT 'SYSTEM';

ALTER TABLE booking_violations
    ADD severity_points INTEGER DEFAULT 1;

ALTER TABLE booking_violations
    ADD penalty_id BIGINT;

ALTER TABLE booking_violations
    ADD CONSTRAINT fk_booking_violations_on_penalty FOREIGN KEY (penalty_id) REFERENCES penalty_records (id);

-- A single booking might have multiple violations (e.g., LATE_CHECK_IN and DAMAGED_EQUIPMENT)
-- or general misconduct might have booking_id = NULL
ALTER TABLE booking_violations
    DROP CONSTRAINT IF EXISTS uc_booking_violations_booking;

-- ==========================================
-- DATA MIGRATION: Bring existing violations into penalty_records
-- ==========================================

-- 1. Backfill existing violations with default values
UPDATE booking_violations
SET source = 'SYSTEM', severity_points = 1
WHERE source IS NULL;
