CREATE TABLE dashboard_daily_snapshots
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date    DATE        NOT NULL UNIQUE,
    total_bookings   BIGINT      NOT NULL DEFAULT 0,
    pending_count    BIGINT      NOT NULL DEFAULT 0,
    approved_count   BIGINT      NOT NULL DEFAULT 0,
    rejected_count   BIGINT      NOT NULL DEFAULT 0,
    cancelled_count  BIGINT      NOT NULL DEFAULT 0,
    completed_count  BIGINT      NOT NULL DEFAULT 0,
    checked_in_count BIGINT      NOT NULL DEFAULT 0,
    new_violations   BIGINT      NOT NULL DEFAULT 0,
    no_show_count    BIGINT      NOT NULL DEFAULT 0,
    active_rooms     BIGINT      NOT NULL DEFAULT 0,
    active_penalties BIGINT      NOT NULL DEFAULT 0,
    computed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE room_utilization_snapshots
(
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id        BIGINT       NOT NULL REFERENCES classrooms (id),
    week_start          DATE         NOT NULL,
    booked_slot_count   INT          NOT NULL DEFAULT 0,
    total_slot_capacity INT          NOT NULL DEFAULT 0,
    utilization_pct     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    total_bookings      BIGINT       NOT NULL DEFAULT 0,
    avg_attendees       NUMERIC(5, 2),
    computed_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (classroom_id, week_start)
);

CREATE TABLE violation_daily_snapshots
(
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date      DATE         NOT NULL,
    violation_type     VARCHAR(50)  NOT NULL,
    violation_count    BIGINT       NOT NULL DEFAULT 0,
    total_severity_pts BIGINT       NOT NULL DEFAULT 0,
    computed_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (snapshot_date, violation_type)
);
