CREATE TABLE booking_violations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    booking_id  BIGINT,
    type        VARCHAR(255),
    reason      VARCHAR(500)                            NOT NULL,
    resolved_at timestamptz DEFAULT NOW(),
    CONSTRAINT pk_booking_violations PRIMARY KEY (id)
);

ALTER TABLE booking_violations
    ADD CONSTRAINT uc_booking_violations_booking UNIQUE (booking_id);

ALTER TABLE booking_violations
    ADD CONSTRAINT FK_BOOKING_VIOLATIONS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

CREATE TABLE booking_time_slots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at   timestamptz,
    created_at   timestamptz DEFAULT NOW(),
    updated_at   timestamptz DEFAULT NOW(),
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    booking_id   BIGINT                                  NOT NULL,
    time_slot_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_booking_time_slots PRIMARY KEY (id)
);

ALTER TABLE booking_time_slots
    ADD CONSTRAINT FK_BOOKING_TIME_SLOTS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE booking_time_slots
    ADD CONSTRAINT FK_BOOKING_TIME_SLOTS_ON_TIME_SLOT FOREIGN KEY (time_slot_id) REFERENCES time_slots (id);

ALTER TABLE bookings
    ADD cancelled_by VARCHAR(50);
